name: "Publish Docker image"

on: push

jobs:
  push_to_registry:
    name: "Push Docker image to Docker Hub"
    runs-on: ubuntu-latest
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v4.0.0
        with:
         platforms: 'arm64,arm,amd64'
         
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: "Log in to Docker Hub"
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Extract metadata (tags, labels) for Docker"
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: reddexx1989/abba
          flavor: |
            latest=true
            
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2 
        
      - name: "Build and push Docker image"
        uses: docker/build-push-action@v4.2.1
        with:
          platforms: linux/amd64,linux/arm/v6,linux/arm64
          context: docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
